apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass123
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppass123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MYSQL_DATABASE: appdb
  DB_HOST: mysql
  DB_PORT: "3306"

